/**
 * Application Constants
 * Centralizes UI constants, language definitions, and translation thresholds.
 */

export const ON_DEMAND_FALLBACK_COUNT = 4;

export const SUPPORTED_TARGET_LANGUAGES = [
  { code: 'en', name: 'English', color: '#3b82f6' },
  { code: 'es', name: 'Spanish (Español)', color: '#ef4444' },
  { code: 'fr', name: 'French (Français)', color: '#8b5cf6' },
  { code: 'de', name: 'German (Deutsch)', color: '#f59e0b' },
  { code: 'it', name: 'Italian (Italiano)', color: '#10b981' },
  { code: 'pt', name: 'Portuguese (Português)', color: '#06b6d4' },
  { code: 'ru', name: 'Russian (Русский)', color: '#ec4899' },
  { code: 'ja', name: 'Japanese (日本語)', color: '#f43f5e' },
  { code: 'ko', name: 'Korean (한국어)', color: '#6366f1' },
  { code: 'zh-CN', name: 'Chinese Simplified (简体中文)', color: '#e11d48' },
  { code: 'zh-TW', name: 'Chinese Traditional (繁體中文)', color: '#ea580c' },
  { code: 'ar', name: 'Arabic (العربية)', color: '#14b8a6' },
  { code: 'he', name: 'Hebrew (עברית)', color: '#0284c7' },
  { code: 'hi', name: 'Hindi (हिन्दी)', color: '#d97706' },
  { code: 'tr', name: 'Turkish (Türkçe)', color: '#be123c' },
  { code: 'nl', name: 'Dutch (Nederlands)', color: '#84cc16' },
  { code: 'pl', name: 'Polish (Polski)', color: '#a855f7' },
  { code: 'sv', name: 'Swedish (Svenska)', color: '#0ea5e9' },
  { code: 'no', name: 'Norwegian (Norsk)', color: '#38bdf8' },
  { code: 'da', name: 'Danish (Dansk)', color: '#f43f5e' },
  { code: 'fi', name: 'Finnish (Suomi)', color: '#0284c7' },
  { code: 'vi', name: 'Vietnamese (Tiếng Việt)', color: '#10b981' },
  { code: 'th', name: 'Thai (ไทย)', color: '#ca8a04' },
  { code: 'el', name: 'Greek (Ελληνικά)', color: '#2563eb' },
  { code: 'uk', name: 'Ukrainian (Українська)', color: '#eab308' },
  { code: 'cs', name: 'Czech (Čeština)', color: '#059669' },
  { code: 'ro', name: 'Romanian (Română)', color: '#f97316' },
  { code: 'hu', name: 'Hungarian (Magyar)', color: '#10b981' },
  { code: 'id', name: 'Indonesian (Bahasa Indonesia)', color: '#ef4444' },
  { code: 'ms', name: 'Malay (Bahasa Melayu)', color: '#06b6d4' },
  { code: 'tl', name: 'Tagalog / Filipino', color: '#8b5cf6' },
  { code: 'bn', name: 'Bengali (বাংলা)', color: '#10b981' },
  { code: 'pa', name: 'Punjabi (ਪੰਜਾਬੀ)', color: '#f59e0b' },
  { code: 'mr', name: 'Marathi (मराठी)', color: '#ea580c' },
  { code: 'gu', name: 'Gujarati (ગુજરાતી)', color: '#06b6d4' },
  { code: 'ta', name: 'Tamil (தமிழ்)', color: '#ec4899' },
  { code: 'te', name: 'Telugu (తెలుగు)', color: '#6366f1' },
  { code: 'kn', name: 'Kannada (ಕನ್ನಡ)', color: '#eab308' },
  { code: 'ml', name: 'Malayalam (മലയാളം)', color: '#14b8a6' },
  { code: 'ur', name: 'Urdu (اردو)', color: '#059669' },
  { code: 'fa', name: 'Persian (فارسی)', color: '#d97706' },
  { code: 'bg', name: 'Bulgarian (Български)', color: '#10b981' },
  { code: 'hr', name: 'Croatian (Hrvatski)', color: '#3b82f6' },
  { code: 'sr', name: 'Serbian (Српски)', color: '#ef4444' },
  { code: 'sk', name: 'Slovak (Slovenčina)', color: '#8b5cf6' },
  { code: 'sl', name: 'Slovenian (Slovenščina)', color: '#06b6d4' },
  { code: 'lt', name: 'Lithuanian (Lietuvių)', color: '#eab308' },
  { code: 'lv', name: 'Latvian (Latviešu)', color: '#be123c' },
  { code: 'et', name: 'Estonian (Eesti)', color: '#3b82f6' },
  { code: 'ca', name: 'Catalan (Català)', color: '#f59e0b' },
  { code: 'eu', name: 'Basque (Euskara)', color: '#059669' },
  { code: 'gl', name: 'Galician (Galego)', color: '#0ea5e9' },
  { code: 'ga', name: 'Irish (Gaeilge)', color: '#10b981' },
  { code: 'cy', name: 'Welsh (Cymraeg)', color: '#ef4444' },
  { code: 'is', name: 'Icelandic (Íslenska)', color: '#2563eb' },
  { code: 'sw', name: 'Swahili (Kiswahili)', color: '#14b8a6' },
  { code: 'af', name: 'Afrikaans', color: '#f97316' },
  { code: 'hy', name: 'Armenian (Հայերեն)', color: '#8b5cf6' },
  { code: 'ka', name: 'Georgian (ქართული)', color: '#be123c' },
  { code: 'az', name: 'Azerbaijani (Azərbaycan)', color: '#06b6d4' },
  { code: 'kk', name: 'Kazakh (Қазақ)', color: '#0ea5e9' },
  { code: 'uz', name: 'Uzbek (Oʻzbek)', color: '#10b981' },
  { code: 'mn', name: 'Mongolian (Монгол)', color: '#ef4444' },
  { code: 'ne', name: 'Nepali (नेपाली)', color: '#ec4899' },
  { code: 'si', name: 'Sinhala (සිංහල)', color: '#d97706' },
  { code: 'my', name: 'Burmese (မြန်မာ)', color: '#f59e0b' },
  { code: 'km', name: 'Khmer (ខ្មែរ)', color: '#2563eb' },
  { code: 'lo', name: 'Lao (ລາວ)', color: '#059669' },
  { code: 'sq', name: 'Albanian (Shqip)', color: '#be123c' },
  { code: 'mk', name: 'Macedonian (Македонски)', color: '#eab308' },
  { code: 'bs', name: 'Bosnian (Bosanski)', color: '#3b82f6' },
  { code: 'mt', name: 'Maltese (Malti)', color: '#ef4444' },
  { code: 'la', name: 'Latin (Latina)', color: '#8b5cf6' },
  { code: 'eo', name: 'Esperanto', color: '#10b981' },
  { code: 'yi', name: 'Yiddish (ייִדיש)', color: '#6366f1' },
];

export const UI_TEXT = {
  APP_TITLE: 'YouTube Subtitle & Speech Flow Viewer',
  CAPTIONS_ON: 'CC: ON',
  CAPTIONS_OFF: 'Turn CC ON',
  DETECTING_SUBTITLES: 'Detecting subtitles...',
  FETCH_SUBTITLES: 'Fetch Subtitles / CC',
  BACK_CHANGE_VIDEO: 'Back / Change Video',
  CHANGE_TARGET_LANG: 'Change Target Language',
  SETTINGS: 'Settings',
  PLAY: 'Play',
  PAUSE: 'Pause',
  MUTE: 'Mute',
  UNMUTE: 'Unmute',
  NAVBAR_BRAND: 'Language Learning',
  NAVBAR_LIBRARY: 'Library',
  NAVBAR_SHARE: 'Share',
  RESTORED_CACHED_SUBTITLES: (count: number) => `Restored ${count} cached subtitles`,
  SAVED_SUBTITLES_TO_CACHE: (count: number) => `Saved ${count} subtitles to cache`,
  AUTO_DETECTED_SUBTITLES: (count: number) => `Auto-detected ${count} subtitles`,
  SUBTITLE_PLACEHOLDER_ACTIVE: 'Captions active • Spoken dialogue will appear here',
  SUBTITLE_PLACEHOLDER_OFF: 'Turn captions ON to detect dialogue',
  NON_YOUTUBE_LINK_WARNING: 'The shared link is not a YouTube URL. The app only accepts YouTube links (youtube.com, youtu.be, shorts, live, embed).',
  TLANG_FETCH_SUCCESS: (langs: string[]) => `Target translations (${langs.join(', ').toUpperCase()}) fetched via tlang`,
  TLANG_FETCH_PARTIAL: (succeeded: number, total: number) => `Target translations via tlang: ${succeeded}/${total} succeeded`,
  TLANG_FETCH_FAILED: 'Target translation via tlang was not available for this track',
  LINK_PLACEHOLDER: 'Paste any YouTube URL (watch, youtu.be, shorts, live, embed, iframe, timestamp, etc.)',
  CLEAR_INPUT: 'Clear input',
  PASTE_CLIPBOARD: 'Paste from clipboard',
  PASTE: 'Paste',
  RECOGNIZED: 'Recognized:',
  VIDEO_ID: 'ID:',
  STARTS_AT: (timestamp: string, seconds: number) => `Starts at ${timestamp} (${seconds}s)`,
  LINK_REQUIRED: 'Please paste a YouTube link or video ID',
  YOUTUBE_LINK_NOT_RECOGNIZED: 'Could not recognize a YouTube video in the provided text. The app only supports YouTube links.',
  PASTED_LINK_NOT_YOUTUBE: 'The pasted link is not a YouTube link. Only YouTube links can be played.',
  CLIPBOARD_ACCESS_DENIED: 'Clipboard access denied. Please paste manually into the input box.',
  PLAYLIST_ATTACHED: 'Playlist Attached',
  SHARE_LINK_WITH_APP: 'Share Link with App',
  OPEN_LIBRARY: 'Open cached video and subtitles library',
  MY_LIBRARY: (count?: number) => `My Library${count !== undefined ? ` (${count})` : ''}`,
  DEMO: 'Demo:',
  PASTE_URL_HINT: 'Paste any YouTube URL or video ID (standard, shorts, embed, timestamped)',
  OFFLINE_NOTICE: 'Offline: YouTube streaming requires an active internet connection.',
  BACK_LIBRARY: 'Back / Library',
  SELECT_TARGET_LANGUAGE: 'Select Target Translation Language',
  BROWSE_CACHED_FILES: 'Browse Cached Multi-lingual JSON3 Files',
  ACTIVITY_LOGS: 'Activity Logs & Diagnostics',
  EXIT_THEATER_MODE: 'Exit Theater Mode',
  THEATER_MODE: 'Theater Mode',
  VIDEO_TIMELINE_PROGRESS: 'Video timeline progress',
  AUTO_TTS_ON: 'Auto-TTS Narration is ON',
  AUTO_TTS_OFF: 'Turn Auto-TTS Narration ON',
  TTS_ON: 'TTS: ON',
  TTS_OFF: 'TTS: OFF',
  CAPTIONS_ARE_ON: 'Captions are ON',
  DETECTING: 'Detecting...',
  NARRATING: (language: string) => `Narrating: ${language} (JSON3)`,
  PLAYING_VIDEO_DIALOGUE: 'Playing Video Dialogue',
  SPEECH_FLOW_READY: 'Speech Flow: Ready',
  TARGET_JSON3: 'Target JSON3:',
  SWITCH_TARGET_JSON3: (language: string) => `Switch target JSON3 track to ${language}`,
  PAUSE_SENTENCE_SYNC: 'Pause Sentence Sync',
  START_DUAL_LANGUAGE_SYNC: 'Start Dual-Language Sync',
  LOOP_ACTIVE_CUE: 'Loop active sentence and translation',
  LOOP_CUE: 'Loop Cue',
  PREVIOUS_CUE: 'Previous JSON3 cue',
  NEXT_CUE: 'Next JSON3 cue',
  PREV: 'Prev',
  NEXT: 'Next',
  SPEAK_JSON3_CUE: 'Speak JSON3 Cue',
} as const;
